title: Curso de WordPress
author:
  name: Guillermo Vera Amaro
  email: "gvera@uv.mx"

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Material para el curso-taller de WordPress.

# Build settings

# If you clone the Minima repo and build locally, use this setting.
#theme: minima
#theme: jekyll-theme-minimal

# As of November 2023, GitHub Pages still uses Minima 2.5.1 (https://pages.github.com/versions/). 
# If you want to use the latest Minima version on GitHub Pages, use the following setting and 
# add a line comment on "theme: minima" above.
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

lang: es

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
header_pages:
  - index.md
  - about.md

# Set to `true` to show excerpts on the homepage.
#show_excerpts: false
